#use_frameworks!

platform :ios, '9.0'

target 'LDZFWechatOpenSDK_Example' do
  pod 'LDZFWechatOpenSDK', :path => '../'

  target 'LDZFWechatOpenSDK_Tests' do
    inherit! :search_paths

    
  end
end
